[phases.setup]
nixPkgs = ["wget", "gnupg", "chromium"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = "python ranking.py"