[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "wget", "gnupg", "chromium"]
nixOverlays = []
nixpkgsArchive = "nixos-23.11"

[phases.install]
dependsOn = ["setup"]
cmds = [
  # Use Nix's Python to run pip
  "/nix/store/*/bin/python3 -m ensurepip --upgrade",
  "/nix/store/*/bin/python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python3 ranking.py"