[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "wget", "gnupg", "chromium"]
nixOverlays = []
nixpkgsArchive = "nixos-23.11"

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python3 -m pip install --upgrade pip setuptools --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python3 ranking.py"