[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "wget", "gnupg", "chromium"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = "python ranking.py"