[phases.setup]
aptPkgs = [
  "wget",
  "gnupg",
  "unzip",
  "libglib2.0-0",
  "libnss3",
  "libgconf-2-4",
  "libfontconfig1",
  "xvfb"
] 

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = "xvfb-run -a python ranking.py"