[phases.setup]
commands = [
    "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb", # Download Chrome
    "dpkg -i google-chrome-stable_current_amd64.deb",  # Install Chrome
    "apt-get install -f",  # Fix dependencies
]
