name: Daily ATP Rankings Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  update_rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history to ensure proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}-v3
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install undetected-chromedriver selenium pandas

      - name: Run ranking update script
        env:
          # Add environment variables that might be needed for headless Chrome
          PYTHONUNBUFFERED: 1
          DISPLAY: :99
        run: |
          echo "Running ranking script..."
          # Add export for headless mode
          export HEADLESS=true
          python ranking.py
        
      # NEW STEP: Force a file change to ensure there's something to commit
      - name: Create timestamp file
        run: |
          echo "ATP Rankings last checked: $(date)" > last_check.txt

      - name: Commit and push changes if any
        run: |
          # This will now always have at least the timestamp file to commit
          git add -A
          git commit -m "Automated ATP rankings update for $(date +'%Y-%m-%d')"
          git push
          echo "Changes pushed successfully!"