name: Daily ATP Rankings Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  update_rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history to ensure proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Create output directories
        run: |
          mkdir -p atp_rankings_data

      - name: Run ranking update script
        run: |
          echo "Running ranking script..."
          python ranking.py
          
      - name: Display git status for debugging
        run: |
          git status
          echo "Changes in files:"
          git diff --stat

      - name: Force commit and push changes
        run: |
          # Always create a commit by updating the timestamp file
          echo "Last checked: $(date)" > last_check.txt
          git add -A
          git commit -m "ATP rankings update for $(date +'%Y-%m-%d')"
          git push
          echo "Changes pushed successfully!"