name: Daily ATP Rankings Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  update_rankings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') || 'default' }}-v3
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Set up Chrome with specific version
        uses: browser-actions/setup-chrome@v1 
        with:
          chrome-version: '133.0.6943.0'  # Set the required version of Chrome (make sure this matches)

      - name: Install chromedriver
        run: |
          # Get the installed Chrome version
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          
          # Fetch the matching chromedriver version
          CHROMEDRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          # Check if the version was fetched successfully
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to fetch Chromedriver version for Chrome $CHROME_VERSION"
            exit 1
          fi

          # Download and install chromedriver matching the installed chrome version
          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install undetected-chromedriver selenium webdriver-manager pandas

      - name: Start virtual display (Xvfb)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3

      - name: Run ranking update script
        env:
          DISPLAY: :99
          PYTHONUNBUFFERED: 1
        run: python ranking.py

      - name: Create timestamp file
        run: |
          echo "ATP Rankings last checked: $(date +'%Y-%m-%d')" > last_check.txt

      - name: Ensure latest changes are pulled
        run: |
          BRANCH=$(git symbolic-ref --short HEAD)
          git pull --rebase origin $BRANCH || (git fetch --all && git reset --hard origin/$BRANCH)

      - name: Commit and push changes if any
        run: |
          git add -A
          git commit -m "Automated ATP rankings update for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin $BRANCH || echo "Push failed, likely no new changes."
